### ISSUE TITLE
Taskify : Fix the Search bar of the Dashboard

### ISSUE THREAD

**Issue by Rupam-Matabber** [DSCKGEC/Taskify#19]
![image](https://user-images.githubusercontent.com/78860897/180860478-7b362eda-2c50-42e1-aee4-527cf310bae9.png)

- Fix the search bar of the dashboard page.
- Make it fixed on the top position.
- Replace the images of the search bar with font awesome icons.
- Use the above picture for design reference.

**Comment by Villain45** [comment]
I would like to work on this issue

**Comment by Rupam-Matabber** [comment]
Assigned to you @Villain45. Best of luck.
